apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-admin
  namespace: microkafka
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-admin
          image: localhost:32000/kafka-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka.microkafka.svc.cluster.local:9092,kafka-1.kafka.microkafka.svc.cluster.local:9092,kafka-2.kafka.microkafka.svc.cluster.local:9092
