pipeline {
  agent any

  environment {
    IMAGE_NAME = "ashwinsai22/order-service"
  }

  stages {
    stage('Build') {
      steps {
        sh '''
          cd order-service
          docker build -t $IMAGE_NAME:latest .
        '''
      }
    }

    stage('Push') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:latest
          '''
        }
      }
    }
  }
}
