apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: microkafka
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      process.roles: "broker,controller"
      node.id: "${STRIMZI_BROKER_ID}"
      controller.quorum.voters: |
        0@kafka-0.kafka.microkafka.svc.cluster.local:9093,
        1@kafka-1.kafka.microkafka.svc.cluster.local:9093,
        2@kafka-2.kafka.microkafka.svc.cluster.local:9093
      controller.listener.names: "CONTROLLER"
      listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
      inter.broker.listener.name: "PLAINTEXT"
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
